#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

ANDROID_PACKAGE="br.univates.labmobile.conecta_creche"
WRITTEN_FILES=()

write_credential_file() {
  local dest="$1" src="$2"
  mkdir -p "$(dirname "$dest")"
  cp "$src" "$dest"
  WRITTEN_FILES+=("$dest")
  printf '  %s✓ gravou%s %s\n' "$GREEN" "$RESET" "$dest"
}

firebase_project_url() {
  local path="$1"
  local project="${FIREBASE_PROJECT_ID:-_}"
  printf 'https://console.firebase.google.com/project/%s/%s' "$project" "$path"
}

finish_wizard() {
  _clear
  printf '\n%s%s  ✓ Configuração concluída%s\n' "$BOLD" "$GREEN" "$RESET"
  if (( ${#WRITTEN_FILES[@]} )); then
    note "Arquivos gravados nesta execução:"
    for f in "${WRITTEN_FILES[@]}"; do note "  · $f"; done
  fi
  (( ${#WRITTEN_ENV[@]} )) && note "Valores em $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'
    warn "Ainda manualmente:"
    for s in "${SKIPPED[@]}"; do note "  · $s"; done
  fi
  printf '\n'
  note "Próximo passo: flutter pub get && flutter run"
  note "Referência: docs/credentials.md"
  printf '\n'
}

TOTAL_STAGES=6
TOTAL_MINUTES=20

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter para continuar}" "$RESET"
  read -r _ || true
}

banner "Firebase — Conecta Creche"

# ── 1. Projeto Firebase ───────────────────────────────────────────────────
stage "Projeto Firebase" 3
say "Cada desenvolvedor usa seu próprio projeto Firebase — credenciais ficam só na sua máquina."
open_url "https://console.firebase.google.com/"
step "Entre com sua conta Google."
step "Crie um projeto novo (ex.: conecta-creche-seunome) ou selecione um existente."
step "Anote o ID do projeto em Configurações do projeto → Geral → ID do projeto."
ask FIREBASE_PROJECT_ID "ID do projeto Firebase:"
if [[ -n "${FIREBASE_PROJECT_ID:-}" ]]; then
  write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
else
  SKIPPED+=("definir FIREBASE_PROJECT_ID em .env")
  warn "ID do projeto vazio — URLs das próximas etapas usam o console genérico."
fi
pause "Projeto criado ou selecionado?"

# ── 2. Authentication + Google ────────────────────────────────────────────
stage "Authentication e Google Sign-In" 5
say "Habilite login com Google para o app Conecta Creche."
open_url "$(firebase_project_url "authentication/providers")"
step "Clique em 'Começar' se Authentication ainda não estiver ativo."
step "Na aba 'Sign-in method', abra o provedor 'Google'."
step "Ative o provedor e escolha um e-mail de suporte do projeto (obrigatório)."
step "Salve as alterações."
pause "Google Sign-In habilitado?"

# ── 3. Firestore ──────────────────────────────────────────────────────────
stage "Firestore Database" 3
say "Crie o banco Firestore para usuários e dados do app."
open_url "$(firebase_project_url "firestore")"
step "Clique em 'Criar banco de dados' se ainda não existir."
step "Escolha o modo de produção (as regras versionadas no repo serão aplicadas depois)."
step "Selecione a região mais próxima (ex.: southamerica-east1 — São Paulo)."
pause "Firestore criado?"
note "Promoção de admin (role gestao): edição manual no console — ver docs/credentials.md"

# ── 4. google-services.json ───────────────────────────────────────────────
stage "App Android e google-services.json" 5
say "Registre o app Android e baixe a configuração Google Services."
open_url "$(firebase_project_url "settings/general")"
step "Em 'Seus apps', adicione um app Android (ícone Android)."
step "Package name (applicationId): $ANDROID_PACKAGE"
step "Apelido e SHA-1 são opcionais esta semana — pode pular."
step "Baixe google-services.json quando o console oferecer."
note "Destino no repo: android/app/google-services.json (gitignored)"
ask GOOGLE_SERVICES_SRC "Caminho completo do google-services.json baixado (vazio para pular):"
if [[ -n "${GOOGLE_SERVICES_SRC:-}" ]]; then
  if [[ -f "$GOOGLE_SERVICES_SRC" ]]; then
    write_credential_file "$REPO_ROOT/android/app/google-services.json" "$GOOGLE_SERVICES_SRC"
  else
    SKIPPED+=("copiar google-services.json → android/app/google-services.json")
    warn "Arquivo não encontrado: $GOOGLE_SERVICES_SRC"
  fi
elif [[ -f "$REPO_ROOT/android/app/google-services.json" ]]; then
  note "android/app/google-services.json já existe — mantido."
else
  SKIPPED+=("copiar google-services.json → android/app/google-services.json")
fi
note "iOS (ios/Runner/GoogleService-Info.plist) é opcional esta semana — veja docs/credentials.md"

# ── 5. FlutterFire configure (opcional) ─────────────────────────────────
stage "FlutterFire — firebase_options.dart (opcional)" 2
say "No Android desta semana, só o google-services.json já basta para build e execução."
say "Este passo gera lib/firebase_options.dart — útil no futuro (iOS/web), mas não é obrigatório."
if [[ -f "$REPO_ROOT/android/app/google-services.json" ]]; then
  printf '  %s✓ android/app/google-services.json presente — pode pular o FlutterFire.%s\n' "$GREEN" "$RESET"
fi
note "flutterfire configure exige firebase login. Sem CLI logado, ignore este estágio."
step "Opcional: dart pub global activate flutterfire_cli && firebase login"
step "Opcional: flutterfire configure --project=<id> --platforms=android --out=lib/firebase_options.dart"
if command -v flutterfire >/dev/null 2>&1 && [[ -n "${FIREBASE_PROJECT_ID:-}" ]]; then
  if confirm "Executar flutterfire configure agora (opcional)"; then
    if flutterfire configure \
        --project="$FIREBASE_PROJECT_ID" \
        --platforms=android \
        --yes \
        --out=lib/firebase_options.dart; then
      WRITTEN_FILES+=("lib/firebase_options.dart")
      printf '  %s✓ gerou%s lib/firebase_options.dart\n' "$GREEN" "$RESET"
    else
      note "flutterfire falhou (ex.: sem firebase login) — ok para Android se google-services.json existir."
    fi
  else
    note "FlutterFire ignorado — use só google-services.json no Android."
  fi
elif [[ -f "$REPO_ROOT/lib/firebase_options.dart" ]]; then
  note "lib/firebase_options.dart já existe — mantido."
else
  note "Sem flutterfire/login: pule. android/app/google-services.json é suficiente para flutter run."
fi

# ── 6. Verificar gitignore ────────────────────────────────────────────────
stage "Verificar .gitignore" 2
say "Confirmamos que credenciais não entram no git."
note "Referência: docs/credentials.md"
CREDENTIAL_PATHS=(
  android/app/google-services.json
  lib/firebase_options.dart
  ios/Runner/GoogleService-Info.plist
  secrets/
  .env
)
for p in "${CREDENTIAL_PATHS[@]}"; do
  if git check-ignore -q "$p" 2>/dev/null; then
    printf '  %s✓ ignorado:%s %s\n' "$GREEN" "$RESET" "$p"
  else
    warn "$p não está no .gitignore"
    SKIPPED+=("garantir que $p está no .gitignore")
  fi
done
if git status --short -- \
    android/app/google-services.json \
    lib/firebase_options.dart \
    ios/Runner/GoogleService-Info.plist \
    secrets/ \
    .env 2>/dev/null | grep -q .; then
  warn "git status mostra arquivos sensíveis — não faça commit deles."
else
  printf '  %s✓ git status limpo%s (credenciais não rastreadas)\n' "$GREEN" "$RESET"
fi
say "Teste opcional: touch android/app/google-services.json && git status --short (deve ficar vazio)."
pause "Verificação concluída?"

finish_wizard
